var pc_html = ''
+= '<div class="ingredient_0220" id="pc_0220">'
+= '<div class="product_nutrition_detail_0220">'
+= '<h2 class="more-product_0220 product_nutrition_title_0220">コーンスープ</h2>'
+= '<div class="nutrition-table_0220 product_nutrition_0220">'
+= '<h3>栄養成分<span class="per_product_content_0220">※1食分（16.5g）当り</span></h3>'
+= '<table class="nutrition_display_table_0220">'
+= '<tbody><tr><th>エネルギー</th><td>68kcal</td></tr>'
+= '<tr><th>たんぱく質</th><td>1.0g</td></tr>'
+= '<tr><th>脂質</th><td>1.5g</td></tr>'
+= '<tr><th>炭水化物</th><td>12g</td></tr>'
+= '<tr><th>食塩相当量</th><td>0.7g</td></tr>'
+= '<tr><th>カリウム</th><td>171mg</td></tr>'
+= '<tr><th>リン</th><td>44mg</td></tr>'
+= '</tbody></table>'
+= '<!--//product_nutrition_0220--></div>'
+= '<div class="product_allergen_0220" style="">'
+= '<h3>アレルギー物質（27品目）</h3>'
+= '<p>※本製品にはアレルギー物質のうち、<span class="are_0220">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;　</span>がついているものを含む原材料を使用しています。</p>'
+= '<table>'
+= '<tbody><tr>'
+= '<td>卵</td>'
+= '<td class="are_0220">乳</td>'
+= '<td class="are_0220">小麦</td>'
+= '<td>そば</td>'
+= '<td>落花生</td>'
+= '</tr><tr>'
+= '<td>えび</td>'
+= '<td>かに</td>'
+= '<td>あわび</td>'
+= '<td>いか</td>'
+= '<td>いくら</td>'
+= '</tr><tr>'
+= '<td>オレンジ</td>'
+= '<td>キウイ</td>'
+= '<td>牛肉</td>'
+= '<td>くるみ</td>'
+= '<td>さけ</td>'
+= '</tr><tr>'
+= '<td>さば</td>'
+= '<td class="are_0220">大豆</td>'
+= '<td class="are_0220">鶏肉</td>'
+= '<td>バナナ</td>'
+= '<td class="are_0220">豚肉</td>'
+= '</tr><tr>'
+= '<td>まつたけ</td>'
+= '<td>もも</td>'
+= '<td>やまいも</td>'
+= '<td>りんご</td>'
+= '<td>ゼラチン</td>'
+= '</tr><tr>'
+= '<td>ごま</td>'
+= '<td>カシューナッツ</td>'
+= '<td>-</td>'
+= '<td>-</td>'
+= '<td>-</td>'
+= '</tr>'
+= '</tbody></table>'
+= '<p>※アレルギー物質については原材料名もご確認ください。</p>'
+= '<!--//product_allergen_0220--></div>'
+= '<!--//product_nutrition_detail_0220--></div>'
+= '<div class="product_nutrition_detail_0220">'
+= '<h2 class="more-product_0220 product_nutrition_title_0220">ポタージュ</h2>'
+= '<div class="nutrition-table_0220 product_nutrition_0220">'
+= '<h3>栄養成分<span class="per_product_content_0220">※1食分（15.6g）当り</span></h3>'
+= '<table class="nutrition_display_table_0220">'
+= '<tbody><tr><th>エネルギー</th><td>72kcal</td></tr>'
+= '<tr><th>たんぱく質</th><td>1.0g</td></tr>'
+= '<tr><th>脂質</th><td>3.1g</td></tr>'
+= '<tr><th>炭水化物</th><td>9.9g</td></tr>'
+= '<tr><th>食塩相当量</th><td>0.9g</td></tr>'
+= '<tr><th>カリウム</th><td>136mg</td></tr>'
+= '</tbody></table>'
+= '<!--//product_nutrition_0220--></div>'
+= '<div class="product_allergen_0220" style="">'
+= '<h3>アレルギー物質（27品目）</h3>'
+= '<p>※本製品にはアレルギー物質のうち、<span class="are_0220">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;　</span>がついているものを含む原材料を使用しています。</p>'
+= '<table>'
+= '<tbody><tr>'
+= '<td>卵</td>'
+= '<td class="are_0220">乳</td>'
+= '<td class="are_0220">小麦</td>'
+= '<td>そば</td>'
+= '<td>落花生</td>'
+= '</tr><tr>'
+= '<td>えび</td>'
+= '<td>かに</td>'
+= '<td>あわび</td>'
+= '<td>いか</td>'
+= '<td>いくら</td>'
+= '</tr><tr>'
+= '<td>オレンジ</td>'
+= '<td>キウイ</td>'
+= '<td>牛肉</td>'
+= '<td>くるみ</td>'
+= '<td>さけ</td>'
+= '</tr><tr>'
+= '<td>さば</td>'
+= '<td class="are_0220">大豆</td>'
+= '<td class="are_0220">鶏肉</td>'
+= '<td>バナナ</td>'
+= '<td class="are_0220">豚肉</td>'
+= '</tr><tr>'
+= '<td>まつたけ</td>'
+= '<td>もも</td>'
+= '<td>やまいも</td>'
+= '<td>りんご</td>'
+= '<td>ゼラチン</td>'
+= '</tr><tr>'
+= '<td>ごま</td>'
+= '<td>カシューナッツ</td>'
+= '<td>-</td>'
+= '<td>-</td>'
+= '<td>-</td>'
+= '</tr>'
+= '</tbody></table>'
+= '<p>※アレルギー物質については原材料名もご確認ください。</p>'
+= '<!--//product_allergen_0220--></div>'
+= '<!--//product_nutrition_detail_0220--></div>'
+= '<div class="product_nutrition_detail_0220">'
+= '<h2 class="more-product_0220 product_nutrition_title_0220">かぼちゃ</h2>'
+= '<div class="nutrition-table_0220 product_nutrition_0220">'
+= '<h3>栄養成分<span class="per_product_content_0220">※1食分（16.5g）当り</span></h3>'
+= '<table class="nutrition_display_table_0220">'
+= '<tbody><tr><th>エネルギー</th><td>69kcal</td></tr>'
+= '<tr><th>たんぱく質</th><td>0.9g</td></tr>'
+= '<tr><th>脂質</th><td>1.6g</td></tr>'
+= '<tr><th>炭水化物</th><td>13g</td></tr>'
+= '<tr><th>食塩相当量</th><td>0.6g</td></tr>'
+= '<tr><th>カリウム</th><td>111mg</td></tr>'
+= '<tr><th>リン</th><td>37mg</td></tr>'
+= '</tbody></table>'
+= '<!--//product_nutrition_0220--></div>'
+= '<div class="product_allergen_0220" style="">'
+= '<h3>アレルギー物質（27品目）</h3>'
+= '<p>※本製品にはアレルギー物質のうち、<span class="are_0220">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;　</span>がついているものを含む原材料を使用しています。</p>'
+= '<table>'
+= '<tbody><tr>'
+= '<td>卵</td>'
+= '<td class="are_0220">乳</td>'
+= '<td class="are_0220">小麦</td>'
+= '<td>そば</td>'
+= '<td>落花生</td>'
+= '</tr><tr>'
+= '<td>えび</td>'
+= '<td>かに</td>'
+= '<td>あわび</td>'
+= '<td>いか</td>'
+= '<td>いくら</td>'
+= '</tr><tr>'
+= '<td>オレンジ</td>'
+= '<td>キウイ</td>'
+= '<td>牛肉</td>'
+= '<td>くるみ</td>'
+= '<td>さけ</td>'
+= '</tr><tr>'
+= '<td>さば</td>'
+= '<td class="are_0220">大豆</td>'
+= '<td class="are_0220">鶏肉</td>'
+= '<td>バナナ</td>'
+= '<td class="are_0220">豚肉</td>'
+= '</tr><tr>'
+= '<td>まつたけ</td>'
+= '<td>もも</td>'
+= '<td>やまいも</td>'
+= '<td>りんご</td>'
+= '<td>ゼラチン</td>'
+= '</tr><tr>'
+= '<td>ごま</td>'
+= '<td>カシューナッツ</td>'
+= '<td>-</td>'
+= '<td>-</td>'
+= '<td>-</td>'
+= '</tr>'
+= '</tbody></table>'
+= '<p>※アレルギー物質については原材料名もご確認ください。</p>'
+= '<!--//product_allergen_0220--></div>'
+= '<!--//product_nutrition_detail_0220--></div>'
+= '<!--//ingredient_0220--></div>'
